//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18033
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountStrings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Views.Account.AccountStrings", typeof(AccountStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Formulaire de modification de mot de passe.
        /// </summary>
        public static string ChangePasswordFormTitle {
            get {
                return ResourceManager.GetString("ChangePasswordFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier le mot de passe.
        /// </summary>
        public static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Formulaire d’association.
        /// </summary>
        public static string ExternalLoginConfirmationFormLegend {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmationFormLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S&apos;inscrire.
        /// </summary>
        public static string ExternalLoginConfirmationFormSubmitButtonTitle {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmationFormSubmitButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Associez votre compte {0}..
        /// </summary>
        public static string ExternalLoginConfirmationHeader {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous êtes authentifié avec &lt;strong&gt;{0}&lt;/strong&gt;.
        ///            Veuillez entrer un nom d’utilisateur pour le site ci-dessous, puis cliquer sur le bouton Confirmer pour terminer
        ///            la connexion..
        /// </summary>
        public static string ExternalLoginConfirmationMessage {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S&apos;inscrire.
        /// </summary>
        public static string ExternalLoginConfirmationPageTitle {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se connecter en utilisant votre compte {0}.
        /// </summary>
        public static string ExternalLoginConnectButtonTitle {
            get {
                return ResourceManager.GetString("ExternalLoginConnectButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Échec de la connexion auprès du service..
        /// </summary>
        public static string ExternalLoginFailureErrorMessage {
            get {
                return ResourceManager.GetString("ExternalLoginFailureErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur d’ouverture de session.
        /// </summary>
        public static string ExternalLoginFailurePageTitle {
            get {
                return ResourceManager.GetString("ExternalLoginFailurePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se connecter en utilisant un autre service.
        /// </summary>
        public static string ExternalLoginLegend {
            get {
                return ResourceManager.GetString("ExternalLoginLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun service d’authentification externe n’est configuré. Consultez &lt;a href=\&quot;http://go.microsoft.com/fwlink/?LinkId=252166\&quot;&gt;cet article&lt;/a&gt; pour obtenir des informations sur la configuration de cette application ASP.NET pour la prise en charge de la connexion via des services externes.
        /// </summary>
        public static string ExternalLoginMessageInfo {
            get {
                return ResourceManager.GetString("ExternalLoginMessageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se connnecter.
        /// </summary>
        public static string LoginFormSubmitButtonTitle {
            get {
                return ResourceManager.GetString("LoginFormSubmitButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Formulaire de connexion.
        /// </summary>
        public static string LoginFormTitle {
            get {
                return ResourceManager.GetString("LoginFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se connecter.
        /// </summary>
        public static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string LoginSubTitlePage {
            get {
                return ResourceManager.GetString("LoginSubTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une connexion externe.
        /// </summary>
        public static string ManageAddExternalConnection {
            get {
                return ResourceManager.GetString("ManageAddExternalConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous êtes connecté en tant que &lt;strong&gt;{0}&lt;/strong&gt;..
        /// </summary>
        public static string ManageMessageConnectAs {
            get {
                return ResourceManager.GetString("ManageMessageConnectAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion de compte.
        /// </summary>
        public static string ManagePageTitle {
            get {
                return ResourceManager.GetString("ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gérer le compte.
        /// </summary>
        public static string ManageTitlePage {
            get {
                return ResourceManager.GetString("ManageTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S&apos;inscrire.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Formulaire d’inscription.
        /// </summary>
        public static string RegisterFormLegend {
            get {
                return ResourceManager.GetString("RegisterFormLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string RegisterFormSubmitButtonTitle {
            get {
                return ResourceManager.GetString("RegisterFormSubmitButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création de compte.
        /// </summary>
        public static string RegisterFormTitle {
            get {
                return ResourceManager.GetString("RegisterFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créez un nouveau compte..
        /// </summary>
        public static string RegisterNewAccount {
            get {
                return ResourceManager.GetString("RegisterNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S&apos;enregister.
        /// </summary>
        public static string RegisterPageTitle {
            get {
                return ResourceManager.GetString("RegisterPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer ces informations d’identification {0} de votre compte.
        /// </summary>
        public static string RemoveExternalFormSubmitButtonTitle {
            get {
                return ResourceManager.GetString("RemoveExternalFormSubmitButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexions externes enregistrées.
        /// </summary>
        public static string RemoveExternalLoginHeader {
            get {
                return ResourceManager.GetString("RemoveExternalLoginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Formulaire de définition de mot de passe.
        /// </summary>
        public static string SetPasswordFormLegend {
            get {
                return ResourceManager.GetString("SetPasswordFormLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Définir un mot de passe.
        /// </summary>
        public static string SetPasswordFormSubmitButtonTitle {
            get {
                return ResourceManager.GetString("SetPasswordFormSubmitButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous n’avez pas de mot de passe local pour ce site. Ajoutez un mot de passe local, pour pouvoir vous connecter sans connexion externe..
        /// </summary>
        public static string SetPasswordMessage {
            get {
                return ResourceManager.GetString("SetPasswordMessage", resourceCulture);
            }
        }
    }
}
